"""empty message

Revision ID: 2c8d62004c2d
Revises: 7b365699f553
Create Date: 2017-01-01 13:16:20.769507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c8d62004c2d'
down_revision = '7b365699f553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolio_symbols', 'number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('portfolio_symbols', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolio_symbols', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('portfolio_symbols', 'number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
