"""empty message

Revision ID: 6ad22e7fe839
Revises: a2ecc884e6ce
Create Date: 2016-12-30 21:46:02.561027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad22e7fe839'
down_revision = 'a2ecc884e6ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'description')
    # ### end Alembic commands ###
