"""empty message

Revision ID: 6f0a4d664736
Revises: dfb20654725b
Create Date: 2016-12-30 23:17:10.631257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0a4d664736'
down_revision = 'dfb20654725b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('address', sa.String(), nullable=False))
    op.add_column('stocks', sa.Column('cik', sa.Integer(), nullable=False))
    op.add_column('stocks', sa.Column('date_added', sa.DateTime(), nullable=True))
    op.add_column('stocks', sa.Column('industry', sa.String(), nullable=False))
    op.add_column('stocks', sa.Column('sector', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'sector')
    op.drop_column('stocks', 'industry')
    op.drop_column('stocks', 'date_added')
    op.drop_column('stocks', 'cik')
    op.drop_column('stocks', 'address')
    # ### end Alembic commands ###
